/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as MeRouteImport } from './routes/me'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as LibraryIdRouteImport } from './routes/library.$id'
import { Route as ExprIdRouteImport } from './routes/expr.$id'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/library/$id',
  path: '/library/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExprIdRoute = ExprIdRouteImport.update({
  id: '/expr/$id',
  path: '/expr/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/community': typeof CommunityRouteWithChildren
  '/me': typeof MeRoute
  '/playground': typeof PlaygroundRoute
  '/community/$id': typeof CommunityIdRoute
  '/expr/$id': typeof ExprIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/r/$id': typeof RIdRoute
  '/community/': typeof CommunityIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/me': typeof MeRoute
  '/playground': typeof PlaygroundRoute
  '/community/$id': typeof CommunityIdRoute
  '/expr/$id': typeof ExprIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/r/$id': typeof RIdRoute
  '/community': typeof CommunityIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/community': typeof CommunityRouteWithChildren
  '/me': typeof MeRoute
  '/playground': typeof PlaygroundRoute
  '/community/$id': typeof CommunityIdRoute
  '/expr/$id': typeof ExprIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/r/$id': typeof RIdRoute
  '/community/': typeof CommunityIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cheatsheet'
    | '/community'
    | '/me'
    | '/playground'
    | '/community/$id'
    | '/expr/$id'
    | '/library/$id'
    | '/r/$id'
    | '/community/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cheatsheet'
    | '/me'
    | '/playground'
    | '/community/$id'
    | '/expr/$id'
    | '/library/$id'
    | '/r/$id'
    | '/community'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cheatsheet'
    | '/community'
    | '/me'
    | '/playground'
    | '/community/$id'
    | '/expr/$id'
    | '/library/$id'
    | '/r/$id'
    | '/community/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheatsheetRoute: typeof CheatsheetRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  MeRoute: typeof MeRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ExprIdRoute: typeof ExprIdRoute
  LibraryIdRoute: typeof LibraryIdRoute
  RIdRoute: typeof RIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expr/$id': {
      id: '/expr/$id'
      path: '/expr/$id'
      fullPath: '/expr/$id'
      preLoaderRoute: typeof ExprIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CommunityRouteChildren {
  CommunityIdRoute: typeof CommunityIdRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityIdRoute: CommunityIdRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheatsheetRoute: CheatsheetRoute,
  CommunityRoute: CommunityRouteWithChildren,
  MeRoute: MeRoute,
  PlaygroundRoute: PlaygroundRoute,
  ExprIdRoute: ExprIdRoute,
  LibraryIdRoute: LibraryIdRoute,
  RIdRoute: RIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
